stages:
   - work

test:
    stage: work
    image: golang:1.13
    script: 
     - go mod init feniks
     - go test .

build:
    stage: work
    image: docker:latest
    script:
     - docker build .

